### ISSUE TITLE
[DEM to add] CopernicusDEM

### ISSUE THREAD

**Issue by basaltena** [GLIMS-RGI/rgitools#35]
CopernicusDEM is another global elevation model of interest to include and was initiated within the Copernicus framework. This elevation model will also be used for the orthorectification of Sentinel-2, and it is envisioned that USGS will implement this as well in its pipeline, so Landsat imagery will also be based on this. CopernicusDEM is based upon the WorldDEM from TanDEM (DLR), but it's quality controlled by Airbus, which detected and corrected errors in this elevation model (where infilling was done with the help of SRTM/ASTER GDEM). Only pitfall is the availability of the dataset, as it has an open dataset with a resolution of 90 meters, while a protected version of 30 meter also exists.

for more info see:
https://spacedata.copernicus.eu/web/cscda/data-offer/core-datasets/-/asset_publisher/SMEFUkzOylMw/content/optical-hr-pan-eu-coverages-hr_image_2015-?_101_INSTANCE_SMEFUkzOylMw_redirect=%2Fweb%2Fcscda%2Fdata-offer%2Fcore-datasets

https://eop-cfi.esa.int/index.php/docs-and-mission-data/dem

**Comment by matthiasdusch** [comment]
Thanks @basaltena
This looks very promising and I will definitely look into it. 
Oh, and it seems well documented, clearly states stuff like acquisition date and even has a proper license (proprietary but still better than most): I love it

It might be too new on a global scale for the current RGI which is based around 2000. But if it fulfils its promises it could become the goto DEM for outlines around 2010-2015.
And if the coverage is as good as stated in the high latitudes it might still be a valid alternative in Antarctica.

I'll implement it (in a couple of weeks) and report here about it.
